//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Course()
        {
            this.Tbl_Student = new HashSet<Tbl_Student>();
        }
    
        public int Course_id { get; set; }
        public string Course_name { get; set; }
        public Nullable<int> Dept_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Student> Tbl_Student { get; set; }
        public virtual Tbl_Dept Tbl_Dept { get; set; }
    }
}
